### ISSUE TITLE
A try guarded by except NotImplementedError drops the imports it resolved -- the Adafruit TYPE_CHECKING guard

### ISSUE THREAD

**Issue by begeistert** [PyMCU/PyMCU#480]
## What happens

A module-level `try:`/`except` whose handler names an exception that does not
cover `ImportError` silently drops the names its own try body resolved:

```python
# mod.py
try:
    from pwmio import PWMOut          # resolves -- the import succeeds
except NotImplementedError:
    pass


class Thing:
    def __init__(self, h: PWMOut) -> None:   # refused: unknown type 'PWMOut'
        self._h = h
```

```text
mod.py:8:5: error: CompileError: unknown type 'PWMOut' in the annotation.
An unrecognized annotation used to be read as uint8...
```

`from pwmio import PWMOut` compiles fine on its own, and the same `try` guarded
by `except ImportError:`, `except Exception:` or `except BaseException:` keeps
the binding. `except ValueError:` and `except NotImplementedError:` lose it --
the compile-time fold appears to only keep the try body's names when the
handler could have caught an import failure, and silently skips the body
otherwise instead of reporting that it cannot reason about the guard.

## Why it matters

This is the exact TYPE_CHECKING guard every upstream Adafruit library opens
with. `adafruit_motor/motor.py` and `adafruit_motor/servo.py` both do:

```python
try:
    from types import TracebackType
    from typing import Optional, Type

    try:
        from pwmio import PWMOut
    except NotImplementedError:                          # <-- this except
        from circuitpython_typing.pwmio import PWMOut
except ImportError:
    pass
```

The inner `except NotImplementedError` makes the whole nested `try` drop the
`PWMOut` it just imported, so `def __init__(self, pwm_out: "PWMOut", ...)` and
`def __init__(self, positive_pwm: PWMOut, ...)` are both refused at
`motor.py:63` / `servo.py:41`. Nothing in the diagnostic points at the guard;
the name is reported as an unknown type at its use site.

The failure is also import-form dependent, which makes it harder to recognise:
`import adafruit_motor.motor` and `from adafruit_motor import motor` are refused
outright, and `from adafruit_motor.motor import DCMotor` alone is too -- but
`from adafruit_motor.motor import DCMotor` **plus** `DCMotor(a, b)` compiles,
because the use goes through the inline path where the signature is never
scanned. The same module is refused or accepted depending on whether the class
is instantiated.

Sibling of #461 (which covered a *failing sibling import* inside the try).
Here nothing in the try body fails -- the except clause's type alone decides
whether the resolved names survive.

Tested on `1.0.0-beta1+69a21280`.
