### ISSUE TITLE
A raise after a search loop inside an @inline aborts compilation: FixedDict cannot be read at all

### ISSUE THREAD

**Issue by begeistert** [PyMCU/PyMCU#73]
## What happens

`d[k]` on a `FixedDict` fails to compile. Any program that reads a key without
wrapping the read in `try` is rejected:

```python
from pymcu.types import uint16
from pymcu.collections import FixedDict

def main():
    d = FixedDict(4)
    d[3] = 5
    g: uint16 = d[3]
```

```
main.py:8:1: error: CompileError: KeyError: KeyError
```

The key is present, and the message names the line the user wrote, not the
library method that raised.

## Why

`FixedDict.__getitem__` is `@inline` and ends the way a lookup ends:

```python
while n < self._cap:
    if self._state[i] == 0:
        raise KeyError
    ...
    n = n + 1
raise KeyError          # <- the search ran out
```

`VisitRaise` aborts compilation when a runtime exception is raised inside an
`@inline` expansion, outside `try`, at a branch depth no greater than the depth
recorded when the expansion started. The trailing `raise` is at exactly that
depth: the frontend does not model "the loop exited because it ran out of
probes", so a raise placed after a loop reads as unconditional.

It fires with a run-time key too (`d[k]` where `k` is a volatile read), which
rules out constant folding of the table as the cause.

## Regression

Introduced by 9c20542f ("compile guards work in both directions -- three holes,
one visit order"), whose third part added the abort. `git bisect run` over 45
commits identified it; the published 0.1.0a10 compiler builds the same program.

Consequences measured on clean HEAD: the `fixeddict` fixture stops building, and
with it 13 tests in the pymcu-avr integration suite (4 FixedDict value tests, the
lm35 group that fails for a separate reason, and both differential axes).

## Fix applied

`InlineContext.SawDynamicLoop`, set when an expansion visits a loop whose exit
the compiler cannot predict, and checked by the abort rule. The rule keeps doing
what it was written for (a linear `@inline` body that always raises); a lookup
that probes and then raises no longer counts as unconditional.
